import type { GeoEvent, Source } from '../../src/types/domain';

const wiki = (title: string): Source => ({
  org: 'Wikipedia',
  dataset: title,
  url: `https://en.wikipedia.org/wiki/${encodeURIComponent(title.replace(/ /g, '_'))}`,
  date: new Date().toISOString().slice(0, 10),
});

/**
 * Hand-curated, real historical events with real sources. This is
 * intentionally a tertiary-source (Wikipedia) citation set for a v1 world
 * timeline, not a claim of primary-source scholarship — see
 * docs/DATA_SOURCES.md for the methodology note on this tradeoff.
 *
 * Country tags use *modern* ISO codes for entities that no longer exist in
 * their historical form (e.g. the German Empire is tagged DE), since the
 * MVP does not yet model historical political entities as first-class
 * Country records — see the plan's "historical borders" scoping decision.
 */
export const EVENTS: GeoEvent[] = [
  {
    id: 'congress-of-vienna',
    title: 'Congress of Vienna',
    date: '1814-09-18',
    endDate: '1815-06-09',
    description:
      'European powers redrew the map of Europe after the Napoleonic Wars, establishing a balance-of-power system that shaped the continent for decades.',
    countries: ['AT', 'FR', 'GB', 'RU', 'DE'],
    location: { lat: 48.2082, lng: 16.3738 },
    category: 'treaty',
    importance: 3,
    sources: [wiki('Congress of Vienna')],
  },
  {
    id: 'greek-independence',
    title: 'Greek War of Independence',
    date: '1821-03-25',
    endDate: '1832-05-07',
    description: 'Greece won independence from the Ottoman Empire after a decade-long war, becoming one of the first successful nationalist independence movements in Europe.',
    countries: ['GR', 'TR'],
    location: { lat: 37.9838, lng: 23.7275 },
    category: 'independence',
    importance: 2,
    sources: [wiki('Greek War of Independence')],
  },
  {
    id: 'revolutions-of-1848',
    title: 'Revolutions of 1848',
    date: '1848-02-22',
    endDate: '1849-11-01',
    description: 'A wave of republican and nationalist uprisings swept across Europe, from France to the German and Italian states to the Austrian Empire, reshaping political ideas even where the revolutions themselves failed.',
    countries: ['FR', 'DE', 'AT', 'IT', 'HU'],
    category: 'revolution',
    importance: 3,
    sources: [wiki('Revolutions of 1848')],
  },
  {
    id: 'us-civil-war',
    title: 'American Civil War',
    date: '1861-04-12',
    endDate: '1865-05-09',
    description: 'A war between the United States and eleven breakaway Southern states over slavery and federal power, ending in the abolition of slavery and the preservation of the Union.',
    countries: ['US'],
    category: 'war',
    importance: 3,
    sources: [wiki('American Civil War')],
  },
  {
    id: 'italian-unification',
    title: 'Unification of Italy',
    date: '1861-03-17',
    description: 'The Kingdom of Italy was proclaimed after decades of political and military campaigns to unify the Italian peninsula\'s separate states.',
    countries: ['IT'],
    location: { lat: 41.9028, lng: 12.4964 },
    category: 'formation',
    importance: 2,
    sources: [wiki('Unification of Italy')],
  },
  {
    id: 'meiji-restoration',
    title: 'Meiji Restoration',
    date: '1868-01-03',
    description: 'Imperial rule was restored in Japan, launching rapid industrialization and modernization that transformed it into a major world power within decades.',
    countries: ['JP'],
    category: 'regime-change',
    importance: 2,
    sources: [wiki('Meiji Restoration')],
  },
  {
    id: 'german-unification',
    title: 'Unification of Germany',
    date: '1871-01-18',
    description: 'Following Prussia\'s victory in the Franco-Prussian War, the German states unified into the German Empire, fundamentally altering the European balance of power.',
    countries: ['DE', 'FR'],
    location: { lat: 52.52, lng: 13.405 },
    category: 'formation',
    importance: 3,
    sources: [wiki('Unification of Germany')],
  },
  {
    id: 'scramble-for-africa',
    title: 'Berlin Conference and the Scramble for Africa',
    date: '1884-11-15',
    endDate: '1885-02-26',
    description: 'European powers formalized rules for the colonization of Africa, leading to the partition of nearly the entire continent among a handful of colonial empires.',
    countries: ['DE', 'GB', 'FR', 'NG', 'CD', 'ZA'],
    category: 'diplomatic',
    importance: 3,
    sources: [wiki('Berlin Conference')],
  },
  {
    id: 'ww1-start',
    title: 'Outbreak of World War I',
    date: '1914-07-28',
    description: 'The assassination of Archduke Franz Ferdinand triggered a system of alliances that drew most of Europe\'s great powers into a war that would kill over 15 million people.',
    countries: ['AT', 'DE', 'FR', 'GB', 'RU', 'RS'],
    category: 'war',
    importance: 3,
    sources: [wiki('World War I')],
  },
  {
    id: 'russian-revolution',
    title: 'Russian Revolution',
    date: '1917-03-08',
    endDate: '1917-11-08',
    description: 'Two revolutions toppled the Russian monarchy and then the provisional government, bringing the Bolsheviks to power and setting the stage for the Soviet Union.',
    countries: ['RU'],
    location: { lat: 59.9311, lng: 30.3609 },
    category: 'revolution',
    importance: 3,
    sources: [wiki('Russian Revolution')],
  },
  {
    id: 'ww1-end',
    title: 'End of World War I / Treaty of Versailles',
    date: '1918-11-11',
    endDate: '1919-06-28',
    description: 'An armistice ended the fighting, and the Treaty of Versailles imposed harsh terms on Germany, redrew national borders, and created the League of Nations.',
    countries: ['DE', 'FR', 'GB', 'US', 'AT', 'PL'],
    category: 'treaty',
    importance: 3,
    sources: [wiki('Treaty of Versailles')],
  },
  {
    id: 'indian-independence-movement-start',
    title: 'Non-Cooperation Movement in India',
    date: '1920-09-01',
    description: 'Mahatma Gandhi launched a mass campaign of non-violent resistance against British colonial rule, marking a turning point in the Indian independence movement.',
    countries: ['IN', 'GB'],
    category: 'independence',
    importance: 2,
    sources: [wiki('Non-cooperation movement')],
  },
  {
    id: 'great-depression',
    title: 'The Great Depression',
    date: '1929-10-29',
    endDate: '1939-09-01',
    description: 'A global economic collapse triggered by the Wall Street Crash caused mass unemployment worldwide and reshaped economic policy for a generation.',
    countries: ['US', 'DE', 'GB', 'FR'],
    category: 'economic',
    importance: 3,
    sources: [wiki('Great Depression')],
  },
  {
    id: 'nazi-regime',
    title: 'Nazi seizure of power in Germany',
    date: '1933-01-30',
    description: 'Adolf Hitler was appointed Chancellor of Germany, and the Nazi Party rapidly dismantled democratic institutions to establish a one-party dictatorship.',
    countries: ['DE'],
    category: 'regime-change',
    importance: 3,
    sources: [wiki('Machtergreifung')],
  },
  {
    id: 'ww2-start',
    title: 'Outbreak of World War II',
    date: '1939-09-01',
    description: 'Germany\'s invasion of Poland triggered declarations of war by Britain and France, beginning the deadliest conflict in human history.',
    countries: ['DE', 'PL', 'GB', 'FR'],
    category: 'war',
    importance: 3,
    sources: [wiki('World War II')],
  },
  {
    id: 'un-founded',
    title: 'Founding of the United Nations',
    date: '1945-10-24',
    description: 'Fifty-one countries founded the United Nations in the aftermath of World War II, establishing a global forum for diplomacy, peacekeeping, and international law.',
    countries: ['US', 'GB', 'FR', 'RU', 'CN'],
    location: { lat: 40.7489, lng: -73.968 },
    category: 'organization',
    importance: 3,
    sources: [wiki('United Nations')],
  },
  {
    id: 'ww2-end',
    title: 'End of World War II',
    date: '1945-09-02',
    description: 'Japan\'s formal surrender ended World War II, following Germany\'s surrender in May. The war reshaped the global order and set the stage for the Cold War.',
    countries: ['DE', 'JP', 'US', 'GB', 'RU'],
    category: 'war',
    importance: 3,
    sources: [wiki('End of World War II in Europe')],
  },
  {
    id: 'indian-independence',
    title: 'Independence and Partition of India',
    date: '1947-08-15',
    description: 'British India gained independence and was partitioned into India and Pakistan, triggering one of the largest mass migrations in history amid widespread violence.',
    countries: ['IN', 'PK', 'GB'],
    category: 'independence',
    importance: 3,
    sources: [wiki('Partition of India')],
  },
  {
    id: 'israel-founded',
    title: 'Founding of the State of Israel',
    date: '1948-05-14',
    description: 'Israel declared independence following the UN partition plan for Palestine, immediately triggering the first Arab-Israeli war.',
    countries: ['IL', 'PS', 'EG', 'JO', 'SY', 'LB'],
    location: { lat: 31.7683, lng: 35.2137 },
    category: 'formation',
    importance: 3,
    sources: [wiki('1948 Arab–Israeli War')],
  },
  {
    id: 'nato-founded',
    title: 'Founding of NATO',
    date: '1949-04-04',
    description: 'Twelve North American and European countries formed the North Atlantic Treaty Organization, a collective-defense alliance that became central to Cold War geopolitics.',
    countries: ['US', 'GB', 'FR', 'CA'],
    category: 'organization',
    importance: 3,
    sources: [wiki('NATO')],
  },
  {
    id: 'prc-founded',
    title: 'Founding of the People\'s Republic of China',
    date: '1949-10-01',
    description: 'Mao Zedong proclaimed the People\'s Republic of China after the Communist Party\'s victory in the Chinese Civil War, sending the Nationalist government to Taiwan.',
    countries: ['CN', 'TW'],
    category: 'regime-change',
    importance: 3,
    sources: [wiki("Proclamation of the People's Republic of China")],
  },
  {
    id: 'korean-war',
    title: 'Korean War',
    date: '1950-06-25',
    endDate: '1953-07-27',
    description: 'North Korea\'s invasion of South Korea drew in a UN-led coalition and later China, ending in an armistice that left the peninsula divided along the 38th parallel.',
    countries: ['KR', 'KP', 'CN', 'US'],
    category: 'war',
    importance: 3,
    sources: [wiki('Korean War')],
  },
  {
    id: 'suez-crisis',
    title: 'Suez Crisis',
    date: '1956-10-29',
    endDate: '1957-03-07',
    description: 'Egypt\'s nationalization of the Suez Canal triggered an invasion by Britain, France, and Israel, which ultimately withdrew under US and Soviet pressure — a marker of Britain and France\'s declining global power.',
    countries: ['EG', 'GB', 'FR', 'IL'],
    category: 'war',
    importance: 2,
    sources: [wiki('Suez Crisis')],
  },
  {
    id: 'eu-founded',
    title: 'Treaty of Rome / founding of the EEC',
    date: '1957-03-25',
    description: 'Six European countries signed the Treaty of Rome, establishing the European Economic Community — the direct institutional ancestor of today\'s European Union.',
    countries: ['DE', 'FR', 'IT'],
    category: 'organization',
    importance: 3,
    sources: [wiki('Treaty of Rome')],
  },
  {
    id: 'african-decolonization',
    title: '"Year of Africa": mass African decolonization',
    date: '1960-01-01',
    endDate: '1960-12-31',
    description: 'Seventeen African countries gained independence from colonial rule in a single year, marking the peak of the continent\'s decolonization wave.',
    countries: ['NG', 'CD', 'SN', 'ML', 'MG'],
    category: 'independence',
    importance: 3,
    sources: [wiki('Year of Africa')],
  },
  {
    id: 'berlin-wall-built',
    title: 'Construction of the Berlin Wall',
    date: '1961-08-13',
    description: 'East Germany erected a wall dividing East and West Berlin, becoming the most potent physical symbol of the Cold War\'s division of Europe.',
    countries: ['DE'],
    location: { lat: 52.5163, lng: 13.3777 },
    category: 'political',
    importance: 3,
    sources: [wiki('Berlin Wall')],
  },
  {
    id: 'cuban-missile-crisis',
    title: 'Cuban Missile Crisis',
    date: '1962-10-16',
    endDate: '1962-10-29',
    description: 'A thirteen-day confrontation over Soviet nuclear missiles in Cuba brought the United States and Soviet Union closer to nuclear war than at any other point in the Cold War.',
    countries: ['CU', 'US', 'RU'],
    category: 'diplomatic',
    importance: 3,
    sources: [wiki('Cuban Missile Crisis')],
  },
  {
    id: 'vietnam-war',
    title: 'Vietnam War',
    date: '1955-11-01',
    endDate: '1975-04-30',
    description: 'A prolonged conflict between communist North Vietnam and the US-backed South ended in North Vietnamese victory and the reunification of Vietnam under communist rule.',
    countries: ['VN', 'US'],
    category: 'war',
    importance: 3,
    sources: [wiki('Vietnam War')],
  },
  {
    id: 'oil-crisis-1973',
    title: '1973 Oil Crisis',
    date: '1973-10-17',
    endDate: '1974-03-18',
    description: 'An OPEC oil embargo, imposed in response to Western support for Israel in the Yom Kippur War, quadrupled oil prices and triggered a global economic shock.',
    countries: ['SA', 'US', 'GB', 'DE'],
    category: 'economic',
    importance: 2,
    sources: [wiki('1973 oil crisis')],
  },
  {
    id: 'iranian-revolution',
    title: 'Iranian Revolution',
    date: '1978-01-07',
    endDate: '1979-02-11',
    description: 'Mass protests toppled the Shah of Iran, and the country was reconstituted as an Islamic Republic under Ayatollah Khomeini — reshaping Middle Eastern geopolitics for decades.',
    countries: ['IR'],
    category: 'revolution',
    importance: 3,
    sources: [wiki('Iranian Revolution')],
  },
  {
    id: 'soviet-afghan-war',
    title: 'Soviet–Afghan War',
    date: '1979-12-24',
    endDate: '1989-02-15',
    description: 'The Soviet Union invaded Afghanistan to support its communist government; a decade-long insurgency, backed by the US and others, ended in Soviet withdrawal.',
    countries: ['AF', 'RU', 'US'],
    category: 'war',
    importance: 2,
    sources: [wiki('Soviet–Afghan War')],
  },
  {
    id: 'tiananmen-square',
    title: 'Tiananmen Square protests and crackdown',
    date: '1989-04-15',
    endDate: '1989-06-04',
    description: 'Student-led pro-democracy protests in Beijing were suppressed by the Chinese military, resulting in a still-disputed number of deaths and a lasting political chill.',
    countries: ['CN'],
    location: { lat: 39.9055, lng: 116.3976 },
    category: 'political',
    importance: 2,
    sources: [wiki('1989 Tiananmen Square protests and massacre')],
  },
  {
    id: 'berlin-wall-falls',
    title: 'Fall of the Berlin Wall',
    date: '1989-11-09',
    description: 'East Germany opened its borders, and crowds tore down the Berlin Wall, becoming the defining symbol of the collapse of communism in Eastern Europe.',
    countries: ['DE'],
    location: { lat: 52.5163, lng: 13.3777 },
    category: 'political',
    importance: 3,
    sources: [wiki('Fall of the Berlin Wall')],
  },
  {
    id: 'german-reunification',
    title: 'German Reunification',
    date: '1990-10-03',
    description: 'East and West Germany formally reunified, ending 45 years of division after World War II.',
    countries: ['DE'],
    category: 'formation',
    importance: 3,
    sources: [wiki('German reunification')],
  },
  {
    id: 'gulf-war',
    title: 'Gulf War',
    date: '1990-08-02',
    endDate: '1991-02-28',
    description: 'A US-led coalition expelled Iraqi forces from Kuwait after Iraq\'s invasion and annexation of its smaller neighbor.',
    countries: ['IQ', 'US', 'SA'],
    category: 'war',
    importance: 2,
    sources: [wiki('Gulf War')],
  },
  {
    id: 'ussr-dissolution',
    title: 'Dissolution of the Soviet Union',
    date: '1991-12-26',
    description: 'The Soviet Union formally dissolved into fifteen independent states, ending the Cold War and fundamentally reshaping the geopolitical map of Eurasia.',
    countries: ['RU', 'UA'],
    location: { lat: 55.7558, lng: 37.6173 },
    category: 'dissolution',
    importance: 3,
    sources: [wiki('Dissolution of the Soviet Union')],
  },
  {
    id: 'yugoslav-wars',
    title: 'Yugoslav Wars',
    date: '1991-03-31',
    endDate: '2001-11-12',
    description: 'A series of ethnic conflicts accompanied the breakup of Yugoslavia into independent states, marked by mass atrocities including the Srebrenica genocide.',
    countries: ['RS', 'BA', 'HR', 'SI', 'MK', 'ME', 'XK'],
    category: 'war',
    importance: 3,
    sources: [wiki('Yugoslav Wars')],
  },
  {
    id: 'maastricht-treaty',
    title: 'Maastricht Treaty / founding of the European Union',
    date: '1992-02-07',
    description: 'European Community members signed the Maastricht Treaty, formally establishing the European Union and laying the groundwork for the euro.',
    countries: ['DE', 'FR', 'IT'],
    category: 'organization',
    importance: 3,
    sources: [wiki('Maastricht Treaty')],
  },
  {
    id: 'rwandan-genocide',
    title: 'Rwandan Genocide',
    date: '1994-04-07',
    endDate: '1994-07-15',
    description: 'Extremist Hutu militias killed an estimated 800,000 Tutsi and moderate Hutu over roughly 100 days, one of the fastest and most intensive genocides in modern history.',
    countries: ['RW'],
    category: 'war',
    importance: 3,
    sources: [wiki('Rwandan genocide')],
  },
  {
    id: 'euro-introduced',
    title: 'Introduction of the Euro',
    date: '1999-01-01',
    description: 'Eleven European Union member states adopted the euro as a common currency, with physical notes and coins following in 2002.',
    countries: ['DE', 'FR', 'IT', 'ES'],
    category: 'economic',
    importance: 2,
    sources: [wiki('Euro')],
  },
  {
    id: 'september-11',
    title: 'September 11 attacks',
    date: '2001-09-11',
    description: 'Al-Qaeda hijackers attacked the World Trade Center and the Pentagon, killing nearly 3,000 people and triggering the US-led "War on Terror."',
    countries: ['US', 'AF'],
    location: { lat: 40.7115, lng: -74.0134 },
    category: 'war',
    importance: 3,
    sources: [wiki('September 11 attacks')],
  },
  {
    id: 'iraq-war',
    title: 'Iraq War',
    date: '2003-03-20',
    endDate: '2011-12-18',
    description: 'A US-led coalition invaded Iraq and toppled Saddam Hussein, followed by a prolonged insurgency and sectarian conflict with lasting regional consequences.',
    countries: ['IQ', 'US'],
    category: 'war',
    importance: 3,
    sources: [wiki('Iraq War')],
  },
  {
    id: 'eu-eastern-enlargement',
    title: 'EU Eastern Enlargement',
    date: '2004-05-01',
    description: 'Ten countries, most of them formerly under Soviet influence, joined the European Union in its largest single expansion — reshaping the continent\'s economic and political geography.',
    countries: ['PL', 'CZ', 'HU', 'SK'],
    category: 'organization',
    importance: 2,
    sources: [wiki('2004 enlargement of the European Union')],
  },
  {
    id: 'global-financial-crisis',
    title: 'Global Financial Crisis',
    date: '2008-09-15',
    endDate: '2009-06-01',
    description: 'The collapse of Lehman Brothers triggered the worst global financial crisis since the Great Depression, leading to recessions worldwide and sweeping bank bailouts.',
    countries: ['US', 'GB', 'DE'],
    category: 'economic',
    importance: 3,
    sources: [wiki('2007–2008 financial crisis')],
  },
  {
    id: 'arab-spring',
    title: 'Arab Spring',
    date: '2010-12-18',
    endDate: '2012-12-01',
    description: 'A wave of pro-democracy protests and uprisings swept the Arab world, toppling long-standing rulers in Tunisia, Egypt, Libya, and Yemen and triggering the Syrian civil war.',
    countries: ['TN', 'EG', 'LY', 'SY', 'YE'],
    category: 'revolution',
    importance: 3,
    sources: [wiki('Arab Spring')],
  },
  {
    id: 'syrian-civil-war',
    title: 'Syrian Civil War',
    date: '2011-03-15',
    description: 'A civil war grew out of Arab Spring protests against the Assad government, drawing in regional and global powers and displacing millions of Syrians.',
    countries: ['SY'],
    category: 'war',
    importance: 3,
    sources: [wiki('Syrian civil war')],
  },
  {
    id: 'crimea-annexation',
    title: 'Russian annexation of Crimea',
    date: '2014-02-20',
    endDate: '2014-03-18',
    description: 'Russia annexed Crimea from Ukraine following a disputed referendum, a move not recognized by most of the international community and a direct precursor to the wider Russia-Ukraine conflict.',
    countries: ['RU', 'UA'],
    location: { lat: 45.3453, lng: 34.4697 },
    category: 'war',
    importance: 3,
    sources: [wiki('Annexation of Crimea by the Russian Federation')],
  },
  {
    id: 'brexit-referendum',
    title: 'Brexit referendum',
    date: '2016-06-23',
    description: 'The United Kingdom voted to leave the European Union, beginning a process that concluded with formal withdrawal in January 2020.',
    countries: ['GB'],
    category: 'political',
    importance: 2,
    sources: [wiki('2016 United Kingdom European Union membership referendum')],
  },
  {
    id: 'brexit-complete',
    title: 'United Kingdom formally leaves the European Union',
    date: '2020-01-31',
    description: 'The UK\'s withdrawal from the EU took legal effect, ending 47 years of membership and reshaping UK-EU trade and diplomatic relations.',
    countries: ['GB'],
    category: 'political',
    importance: 2,
    sources: [wiki('Brexit')],
  },
  {
    id: 'covid-pandemic',
    title: 'COVID-19 declared a global pandemic',
    date: '2020-03-11',
    description: 'The World Health Organization declared COVID-19 a pandemic; the resulting lockdowns, over 7 million recorded deaths, and economic disruption reshaped global politics and public health policy.',
    countries: ['CN', 'US', 'IT'],
    category: 'economic',
    importance: 3,
    sources: [wiki('COVID-19 pandemic')],
  },
  {
    id: 'russia-invades-ukraine',
    title: 'Russian invasion of Ukraine',
    date: '2022-02-24',
    description: 'Russia launched a full-scale invasion of Ukraine, triggering Europe\'s largest war since World War II, mass sanctions on Russia, and a major realignment of European security policy.',
    countries: ['RU', 'UA'],
    category: 'war',
    importance: 3,
    sources: [wiki('Russian invasion of Ukraine')],
  },
  {
    id: 'nato-nordic-expansion',
    title: 'Finland and Sweden join NATO',
    date: '2023-04-04',
    endDate: '2024-03-07',
    description: 'Finland and then Sweden abandoned decades of military non-alignment to join NATO in direct response to Russia\'s invasion of Ukraine.',
    countries: ['FI', 'SE'],
    category: 'organization',
    importance: 2,
    sources: [wiki('Enlargement of NATO')],
  },
  {
    id: 'israel-hamas-war',
    title: 'Israel-Hamas War',
    date: '2023-10-07',
    description: 'Hamas\'s attack on Israel and the ensuing war in Gaza caused mass casualties on both sides and triggered a wider regional crisis and international divisions over the conflict.',
    countries: ['IL', 'PS'],
    category: 'war',
    importance: 3,
    sources: [wiki('Israel–Hamas war')],
  },
];
