/**
 * Core domain model. Shapes mirror the JSON files generated by data-pipeline/
 * so a future move to a real database is a straight import, not a redesign.
 */

export interface Source {
  org: string;
  dataset: string;
  url: string;
  /** Year or date the underlying figure refers to (not when we fetched it). */
  date: string;
}

export interface SourcedValue<T> {
  value: T;
  unit?: string;
  source: Source;
  /** ISO date this value was pulled from the source during the build. */
  retrievedAt: string;
}

export type RecognitionStatus =
  | 'un-member'
  | 'un-observer'
  | 'partially-recognized'
  | 'disputed'
  | 'de-facto';

export interface CountryCore {
  id: string; // ISO 3166-1 alpha-2
  iso3: string;
  name: string;
  officialName: string;
  region: string;
  subregion?: string;
  capital?: string;
  flagEmoji: string;
  recognitionStatus: RecognitionStatus;
  /** Whether this country has the deep dataset (economy/military/society/politics) or core fields only. */
  hasDeepData: boolean;
}

export interface CountryStatistics {
  population?: SourcedValue<number>;
  populationDensity?: SourcedValue<number>;
  area?: SourcedValue<number>;
  gdp?: SourcedValue<number>;
  gdpPerCapita?: SourcedValue<number>;
  gdpGrowth?: SourcedValue<number>;
  gdpPpp?: SourcedValue<number>;
  inflation?: SourcedValue<number>;
  unemployment?: SourcedValue<number>;
  militaryExpenditure?: SourcedValue<number>;
  militaryExpenditurePctGdp?: SourcedValue<number>;
  hdi?: SourcedValue<number>;
  lifeExpectancy?: SourcedValue<number>;
  literacyRate?: SourcedValue<number>;
  coastline?: SourcedValue<number>;
}

export interface CountryProfile extends CountryCore {
  languages: string[];
  currency?: string;
  governmentType?: string;
  headOfState?: string;
  headOfGovernment?: string;
  independenceDate?: string;
  neighbors: string[]; // country ids
  borders: string[]; // country ids (alias of neighbors, kept for spec parity)
  statistics: CountryStatistics;
  sources: Source[]; // registry of all sources referenced by this country's fields
}

export type EventCategory =
  | 'war'
  | 'revolution'
  | 'independence'
  | 'treaty'
  | 'formation'
  | 'dissolution'
  | 'economic'
  | 'diplomatic'
  | 'organization'
  | 'regime-change'
  | 'political';

export interface GeoEvent {
  id: string;
  title: string;
  date: string; // ISO date
  endDate?: string;
  description: string;
  countries: string[]; // country ids
  location?: { lat: number; lng: number };
  category: EventCategory;
  importance: 1 | 2 | 3;
  sources: Source[];
}

/** The office an officeholder held, not the person's role in a single event. */
export type OfficeRole = 'head-of-state' | 'head-of-government';

export interface LeadershipTerm {
  id: string;
  role: OfficeRole;
  /** Office title as of today, e.g. "Chancellor of Germany". */
  office: string;
  person: string;
  personQid: string;
  start?: string; // ISO date
  end?: string; // ISO date; absent means still in office
  party?: string;
  /** Elections this term was won at — a re-elected leader has more than one. */
  elections: PoliticalElection[];
}

export interface PoliticalElection {
  id: string;
  label: string;
  date: string; // ISO date
}

/**
 * A country's post-1945 political record, loaded on demand alongside the
 * country profile. Generated by data-pipeline/build-politics.ts.
 */
export interface PoliticalHistory {
  id: string; // country id
  terms: LeadershipTerm[];
  elections: PoliticalElection[];
  sources: Source[];
}

export type RelationshipType =
  | 'alliance'
  | 'trade'
  | 'military'
  | 'diplomatic'
  | 'conflict'
  | 'border';

export interface Relationship {
  id: string;
  type: RelationshipType;
  label: string;
  countries: string[];
  description?: string;
  sources: Source[];
}

export interface DisputedTerritory {
  id: string;
  name: string;
  claimants: string[];
  status: RecognitionStatus;
  description: string;
  sources: Source[];
}

export interface NewsArticle {
  title: string;
  publisher: string;
  publishedAt: string;
  url: string;
  description?: string;
}

export interface NewsResponse {
  articles: NewsArticle[];
  fetchedAt: string;
  stale: boolean;
}
